
server:
    port: 8000


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
